import os

VERSION = "0.0.1"
TOOLS = [ "mingw" ]
PLATFORM = "win64"

CCFLAGS = "-O2"
LFLAGS = ""
SOURCES = [ "linalg/Vector3D.cpp",
            "linalg/VectorN.cpp",
            "linalg/MatrixMN.cpp",
            "io/io.cpp",
            "tests/benchmark-omp.cpp" ]

env = Environment(ENV=os.environ, tools=TOOLS,
                  CXX="C:/Dev/MinGW/x64-4.8.1-posix-seh-rev5/mingw64/bin/g++")
env.Append(CCFLAGS=CCFLAGS)
env.Append(LINKFLAGS=LFLAGS)
env.Program(target="benchmark-omp", source=SOURCES)
